version: '3'
services:
  graphhopper:
    build: .
    ports:
      - 8989:8989
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=shnake
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=shnake
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root