version: '3'
services:
  graphhopper:
    build: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=shnake
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  db:
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - POSTGRES_DB=shnake
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root